{% set name = "pytables" %}
{% set version = "3.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tables/tables-{{ version }}.tar.gz
  sha256: 78abcf413091bc7c1e4e8c10fbbb438d1ac0b5a87436c5b972c3e8253871b6fb
  patches:
    - patches/0001-Don-t-copy-blosc2-in-the-package.patch
    - patches/0002-no-python-blosc2-dep.patch

build:
  number: 0
  entry_points:
    - ptdump = tables.scripts.ptdump:main
    - ptrepack = tables.scripts.ptrepack:main
    - pt2to3 = tables.scripts.pt2to3:main
    - pttree = tables.scripts.pttree:main
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy {{ numpy }}
    - packaging
    - py-cpuinfo
    - cython >=3.0.11
    - blosc {{ blosc }}
    - c-blosc2 {{ c_blosc2 }}
    - hdf5 {{ hdf5 }}
    - lzo {{ lzo }}
    - bzip2 {{ bzip2 }}
    - typing-extensions >=4.4.0
  run:
    - python
    - numpy >=1.20
    - numexpr >=2.6.2
    - packaging
    - py-cpuinfo
    - typing-extensions >=4.4.0
    # all with run_exports
    - blosc
    - c-blosc2
    - hdf5
    - lzo
    - bzip2

test:
  requires:
    - mock
    - pip
    - setuptools
    - py-cpuinfo
  commands:
    - pip check
    - pt2to3 -h
    - ptdump -h
    - ptrepack -h
    - pttree -h

about:
  home: https://www.pytables.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Brings together Python, HDF5 and NumPy to easily handle large amounts of data.
  description: |
    PyTables is a package for managing hierarchical datasets and designed to
    efficiently and easily cope with extremely large amounts of data. PyTables
    is built on top of the HDF5 library, using the Python language and the
    NumPy package.
  doc_url: https://www.pytables.org/
  dev_url: https://github.com/PyTables/PyTables

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - tomkooij
    - scopatz
