{% set name = "pytables" %}
{% set version = "3.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tables/tables-{{ version }}.tar.gz
  sha256: d470263c2e50c4b7c8635a0d99ac1ff2f9e704c24d71e5fa33c4529e7d0ad9c3
  patches:
    - patches/0001-Don-t-copy-blosc2-in-the-package.patch
    - patches/0002-no-python-blosc2-dep.patch

build:
  number: 0
  entry_points:
    - ptdump = tables.scripts.ptdump:main
    - ptrepack = tables.scripts.ptrepack:main
    - pt2to3 = tables.scripts.pt2to3:main
    - pttree = tables.scripts.pttree:main
  skip: true  # [py<39]
  # c-blosc2 is currently not available for s390x
  skip: true  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
    - m2-patch  # [win]
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy {{ numpy }}
    - packaging
    - py-cpuinfo
    - cython 0.29
    - blosc 1.21.3
    - c-blosc2 2.12.0
    - hdf5 1.12.1
    - lzo 2.10
    - bzip2 1.0.8
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - numexpr >=2.6.2
    - packaging
    - py-cpuinfo
    # all with run_exports
    - blosc
    - c-blosc2
    - hdf5
    - lzo
    - bzip2

test:
  requires:
    - mock
    - pip
    - setuptools
    - py-cpuinfo
  commands:
    - pip check
    - pt2to3 -h
    - ptdump -h
    - ptrepack -h
    - pttree -h

about:
  home: https://www.pytables.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Brings together Python, HDF5 and NumPy to easily handle large amounts of data.'
  description: |
    PyTables is a package for managing hierarchical datasets and designed to
    efficiently and easily cope with extremely large amounts of data. PyTables
    is built on top of the HDF5 library, using the Python language and the
    NumPy package.
  doc_url: https://www.pytables.org/
  dev_url: https://github.com/PyTables/PyTables

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - tomkooij
    - scopatz
