{% set version = "3.8.0" %}

package:
  name: pytables
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tables/tables-{{ version }}.tar.gz
  sha256: 34f3fa2366ce20b18f1df573a77c1d27306ce1f2a41d9f9eff621b5192ea8788

build:
  number: 1
  entry_points:
    - ptdump = tables.scripts.ptdump:main
    - ptrepack = tables.scripts.ptrepack:main
    - pt2to3 = tables.scripts.pt2to3:main
    - pttree = tables.scripts.pttree:main
  skip: true  # [py<38]
  ignore_run_exports:
    - zlib
    - lzo     # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy  {{ numpy }}
    - packaging 23.0
    - py-cpuinfo 8.0.0
    - cython 0.29.33
    - blosc2 ~=2.0.0
  run:
    - python
    - numpy {{ numpy }}
    # Keep in sync with tables/req_versions.py and
    # doc/source/usersguide/installation.rst *and*
    # pyproject.toml
    - numexpr >=2.6.2
    # blosc2 wheel is actually only needed when compiling on conda envs.
    # Otherwise, lib comes bundled in PyTables wheels (but it doesn't hurt either).
    - blosc2 ~=2.0.0
    - packaging
    - py-cpuinfo

test:
  requires:
    - mock
    - pip
    - setuptools
  commands:
    - pip check
    - pt2to3 -h
    - ptdump -h
    - ptrepack -h
    - pttree -h

about:
  home: https://www.pytables.org
  license: BSD-3-Clause
  lcense_family: BSD
  license_file: LICENSE.txt
  summary: 'Brings together Python, HDF5 and NumPy to easily handle large amounts of data.'
  description: |
    PyTables is a package for managing hierarchical datasets and designed to
    efficiently and easily cope with extremely large amounts of data. PyTables
    is built on top of the HDF5 library, using the Python language and the
    NumPy package.
  doc_url: https://www.pytables.org/
  dev_url: https://github.com/PyTables

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - tomkooij
    - scopatz
