{% set version = "3.7.0" %}

package:
  name: pytables
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tables/tables-{{ version }}.tar.gz
  sha256: e92a887ad6f2a983e564a69902de4a7645c30069fc01abd353ec5da255c5e1fe

build:
  number: 1
  entry_points:
    - pt2to3 = tables.scripts.pt2to3:main
    - ptdump = tables.scripts.ptdump:main
    - ptrepack = tables.scripts.ptrepack:main
    - pttree = tables.scripts.pttree:main
  skip: true  # [py<36]
  ignore_run_exports:
    - zlib
    - lzo     # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - blosc >=1.4.1
    - bzip2
    - cython >=0.29.21
    - hdf5
    - lzo
    - numexpr >=2.6.2
    - numpy  1.19    # [py==37 or py==38 or py==39]
    - numpy  1.21    # [py==310]
    - packaging
    - setuptools >=42.0
    - wheel
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - blosc >=1.4.1
    - bzip2
    - hdf5 >=1.8.15
    - lzo
    - mock
    - numexpr >=2.6.2
    - packaging
    - zlib
    - zstd  # [win]

test:
  requires:
    - mock
    - pip
    - setuptools
  commands:
    - pip check
    - pt2to3 -h
    - ptdump -h
    - ptrepack -h
    - pttree -h

about:
  home: https://www.pytables.org
  license: BSD-3-Clause
  lcense_family: BSD
  license_file: LICENSE.txt
  summary: 'Brings together Python, HDF5 and NumPy to easily handle large amounts of data.'
  description: |
    PyTables is a package for managing hierarchical datasets and designed to
    efficiently and easily cope with extremely large amounts of data. PyTables
    is built on top of the HDF5 library, using the Python language and the
    NumPy package.
  doc_url: https://www.pytables.org/
  dev_url: https://github.com/PyTables

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - tomkooij
    - scopatz
