# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "haeSLr5WM11/Ay9Q7WZ0AxZp/smp265X0j35KOW8Y0w5Ar+tglWRjAtBccUgiL+DE0v0eADhXULQCyuxySH7zbYXbDckQiLXzfiylXYJFYrSthhEDQfWfXAXz4IwYBO+0uVKf1Vy8uwZLtMn1gt90UHte9EF36vCP4NlJWQsUGPVc6A8WgSvojdJACL0rw5zZYkfDQ/bbYTWlRRJdLy8B+rc7jLDQTHZlba7f9GMc7es8NN5w8z98+tvpWLW4TYS2POiIG4KQmgxbjYCPUjye/GoQZJz2ZtaBYW0q3WaOB1NHNQ0lObBz8G5bK0wRzMVW/5K3ROTu99KzaSiFiEA9W+jVPcr4R5rK3DQ2GtMYrgRDrQNIajypaBfAIxmjSfyy6vnohUeO4CEgG85WV0gtROgy0TRZ3pxvFZ7NL+3pd7ObbgZYUVawKiqahOPVGw280dtILuDb9ORQ5uckCNZhtF4xis75dWUxxwBcG1IUSWJh5kKGkDh0yBpCWQrzd4CKKrFB+TU+oxNsgw/K7si1ZmZDXcgB0QRHWMTv6T9xiCCCr6e4ut7sXGg5ZSIr+rrmlsq06CL4jkwiBkJOdtw29k2bGfNL9QQJJdvsVJlUrsYCfKXioAREjqmy+NPnw6kD5ZF8G0tANUbWbyfURzGR1CzNZdhH8H6a/Z3c2arSQw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml