travis:
  secure:
    BINSTAR_TOKEN: TLuVUKnbBeRdKn/OVAWBWf0pkawgtvg2XHaAZw2e8xRMPbIzIGxcLXweCkVjONB6jMqHGpuC669ClVuKUmKKCPWA8Nu/DCWgtxZAZ8XAmcFj78d0KjiaYcMoPvlOl0hvYzY8IBDKlYmS2uZJdpL794YllPbkOVs2TZ+qDprPwEpwNvkx+lsXORkc2RmpzzbLYOJoZwLoCEGGpNuN2dTevksLTr/NgtTc4hYc7maYwQxRVA7Hto8MOTB+CEwtQHrHM6KYXpZ5hz4877KYTWUnWduKCXKdX2Sr6hirvRNGaV8/qETW/p7HSQmwGHz5JHXQkzbTGcVFoTcHI1puWXuQDpWZwIFkU9G/PPq/YsT7N/S0Og1jpWwN7Ncvxb+KzKFKjQpvthvoB/wVlB1MGFk63MkfgeEPQW1vviIBrj7fulUEMZJTHf5USrOiH5XVPxE8ov1BSu0ChJTsCQvZocpWJhlUBgD1tjgyAz8yXs4GgPQR3tReilNcxyBDzPQBEX7AzBYFG5rQM7Dd/hx33leYPrQZyBuwj5kUlELh19D4zA1yVQFyL2F5VQc7xyKn9Qw9BnX++dFX1q/fMg8mr+XCp7OOL10TSmXfcH6SETU5wBrcM0fpZ1Pbq+J7RZ9AsMCUNdOWbCziNFKsU+sXXaG95p6WZrNpo9u2s47UbU6/djc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
