travis:
  secure:
    BINSTAR_TOKEN: eCxRRjd5f4wjVX15CvMy9mBoc+wGwSFx7Yzg9PdsQH1LRA5/UehsxDvQyC2B2fkMz7vOn/26NIxDitJssxxKZN05pws1yP38xxTHusPLfFj4VHTgTnwC03LMwCXtaZzbddBGoKq30HltjviSOfFkMeEUBOuctTmTZ8aQNH5wartPp4laa5V38NGsJNhJk83QBMyK9eWw/sQXfLIoZIr2g+1sy7ndc/8oVyrgexWenT3K6XlOjAsnFYBJLqM8nnVwd14FNKKZUVppFzPYH24eBWSy4jlAbs23ZPeKLYfGv05v0xrNBR+gjZpUNeyUksh2ndRcSd+9FUGAvedhp0CEoYCOsg5Mnx9Y+A827mLvuDBrrmrI5//4mVenDFpXe8QIDrbuISvprAkkNF+bAwWeysEBZyk1XWAdP0up5losP/riSvFvNNViC0KuxneEWh4ghvQPMOK6L+0uoX54AnjhZTSW/nMY9zhpI/il/SqvBAPsGA0EE3/fTMtcHv6gNNS/wSSfTMhzHl4qWIfV3lPQ3pmxCosimKxi2IvIxSyIyqXyP/5Fb9w4S/hnh74d4pxma6lMhAYS1KwO4D/KCgJznQDwoI1/isZcy+MwGrN0KN6Ll9g0ohEnzuaUlhfccAagxzQAl4KJhcXBKPU8v2fNyqcMfdzh23rhYdz5vf7c3HU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
